## Machine Learning Zoomcamp

### Q1. Pandas version

In [2]:
import pandas as pd

In [3]:
pd.__version__

'3.0.6'

In [12]:
# print(f"my pandas version is" pd.__version__)
print(f"my pandas version is:  {pd.__version__}")
print("my pandas version is:",  pd.__version__)

my pandas version is:  3.0.6
my pandas version is: 3.0.6

### Q2. Records Count

In [15]:
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

--2026-10-16 10:10:46--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv’

car_fuel_efficiency 100%[===================>] 620.29K   851KB/s    in 0.7s

2026-10-16 10:10:48 (851 KB/s) - ‘car_fuel_efficiency_2026.csv’ saved [635180/635180]

In [17]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')

### Q2. Records count ||10000

In [23]:
print(f"count rows : {len(df)}")
print(f"df shape : {df.shape[0]}")

count rows : 10000
df shape : 10000

### Q3. Fuel types || 3

In [28]:
df['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

### Q4. Missing values || 2

In [29]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

### Q6 Median value of horsepower || Yes, it decreased

In [30]:
df.horsepower.median()

np.float64(254.0)

In [31]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")
df["horsepower"].isnull().sum()

np.int64(877)

In [35]:
median_before = df["horsepower"].median()
mode_value = df["horsepower"].mode()[0]

median_before, mode_value

(np.float64(254.0), np.float64(252.0))

In [36]:
df["horsepower"] = df["horsepower"].fillna(mode_value)
median_after = df["horsepower"].median()

median_before, median_after

(np.float64(254.0), np.float64(252.0))

### Q7. Sum of weights |||  0.36919696904925486

In [43]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")

In [44]:
df["origin"].unique()

<StringArray>
['Europe', 'Asia', 'USA']
Length: 3, dtype: str

In [46]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [47]:
df_asia = df[df["origin"] == "Asia"]
df_asia.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             265
vehicle_weight           0
acceleration             0
fuel_efficiency_mpg      0
dtype: int64

In [50]:
df_sel = df_asia[["vehicle_weight", "model_year"]]
df_sel

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [51]:
df_7 = df_sel.head(7)
df_7

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [52]:
X = df_7.to_numpy()
X.shape

(7, 2)

In [53]:
XTX = X.T.dot(X)
XTX.shape    # harus (2, 2)

(2, 2)

In [56]:
import numpy as np

In [57]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv.dot(XTX)       # cek: harusnya mendekati matriks identitas

array([[ 1.00000000e+00, -7.77917769e-15],
       [-8.75935812e-14,  1.00000000e+00]])

In [58]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y.shape      # (7,)

(7,)

In [59]:
w = XTX_inv.dot(X.T).dot(y)
w.shape

(2,)

In [60]:
w.sum()

np.float64(0.36919696904925486)